### ISSUE TITLE
Not working after new update

### ISSUE THREAD

**Issue by chiowa** [nitroquery/NitroDashboard#10]
[    ScriptEngine] [19:18:20]  src/Gauge.as (15, 13) :  ERR : Identifier 'ESceneVehicleVisReactorBoostLvl' is not a data type in namespace 'Nitro' or parent
[    ScriptEngine] [19:18:20]  Script compilation failed!
[    ScriptEngine] [19:22:18]  src/Gauge.as (15, 13) :  ERR : Identifier 'ESceneVehicleVisReactorBoostLvl' is not a data type in namespace 'Nitro' or parent
[    ScriptEngine] [19:22:18]  Script compilation failed!

**Comment by nitroquery** [comment]
Thanks for reporting and logs. Will publish fix after I have confirmed that there are no other breaking changes in last update.
